# Generated by Django 3.1.6 on 2021-02-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_auto_20210208_2142"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
    ]
