# Generated by Django 3.1.6 on 2021-02-09 14:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_auto_20210208_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="talker",
            field=models.CharField(default="talker", max_length=20, null=True),
        ),
    ]
