default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .static
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
    - src/applications/main/static/
    - src/applications/onboarding/static/
    - src/applications/profile/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
    - src/applications/main/templates/
    - src/applications/onboarding/templates/
    - src/applications/profile/templates/
  MODE_DEBUG: true
  MODE_PROFILING: false
  HOST: ""
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0

  GOOGLE_CLIENT_ID: ""
  GOOGLE_SECRET: ""

  VK_CLIENT_ID: ""
  VK_SECRET: ""
  VK_KEY: ""

  TELEGRAM_API_ID: ""
  TELEGRAM_API_HASH: ""
  TELEGRAM_TOKEN: ""


development:
  PORT: 8000
  HOST: "localhost"
  SECRET_KEY: "1"


ci:
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  HOST: "inter-network.herokuapp.com"
  MODE_DEBUG: false
  VENV_SYNTHETIC: true
