# Generated by Django 3.1.6 on 2021-02-07 16:07

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, default="default_user.png", null=True, upload_to=""
                    ),
                ),
                ("sity", models.CharField(blank=True, max_length=30, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("needed_help", models.TextField(blank=True, null=True)),
                ("provide_help", models.TextField(blank=True, null=True)),
                (
                    "contacts",
                    models.ManyToManyField(
                        related_name="_profile_contacts_+", to="profile.Profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
