# Generated by Django 3.1.5 on 2021-01-27 15:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
