# Generated by Django 3.1.6 on 2021-02-12 02:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
