# Generated by Django 3.1.5 on 2021-01-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_auto_20210120_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
