# Generated by Django 3.1.5 on 2021-01-20 15:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_auto_20210120_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
